# -*- coding: utf-8 -*-
"""Bokeh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qRLe1kky7XPBZCpEDLNA-GxQzZ8HYAIh
"""

import bokeh.io
import bokeh.plotting
bokeh.io.output_notebook()

pip install bokeh

from bokeh.plotting import figure, output_file, show
from bokeh.sampledata.iris import flowers

output_file('test.html')

p = figure(title = "test flower")
p.xaxis.axis_label = "paltel length"
p.yaxis.axis_label = "paltel width"
p.circle(flowers['petal_length'], flowers['petal_width'])
show(p)

flowers

from bokeh.plotting import figure, output_file, show
from bokeh.sampledata.iris import flowers

output_file('line .html')

p = figure(title = "line graph")
p.xaxis.axis_label = "x axis"
p.yaxis.axis_label = "y axis"
p.line(flowers['petal_length'], flowers['petal_width'])
show(p)

x = [2,3,4,5,6]
y = [3,4,5,6,7]
output_file("line.html")
p = figure(title = "line plot")
p.line(x,y)
show(p)

x = [2,3,4,5,6]
y = [3,4,5,6,7]
output_file("line.html")
p = figure(title = "line plot")
p.scatter(x,y, )
show(p)



x = [2,3,4,5,6]
y = [3,4,5,6,7]
output_file("line.html")
p = figure(title = "line plot")
p.scatter(x,y, fill_color = 'red')
show(p)

x = [2,3,4,5,6]
y = [3,4,5,6,7]
output_file("line.html")
p = figure(title = "line plot")
p.scatter(x,y, fill_color = 'red', legend_label = 'red points')
show(p)

x = [2,3,4,5,6]
y = [3,4,5,6,7]
output_file("line.html")
p = figure(title = "line plot")
p.scatter(x,y, fill_color = 'red', legend_label = 'red points', size = 20)
show(p)

